# Generated by Django 5.0.1 on 2024-02-13 09:33

import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LatestRelease',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=500, null=True)),
                ('image', models.ImageField(upload_to='admin_app/latestrelease')),
                ('text', django_ckeditor_5.fields.CKEditor5Field(verbose_name='Text')),
            ],
        ),
    ]
