# Generated by Django 5.0.1 on 2024-02-13 11:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='latestrelease',
            name='image',
        ),
    ]
