# Generated by Django 5.0.1 on 2024-02-14 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0004_alter_latestrelease_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='latestrelease',
            name='author',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='latestrelease',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
