# Generated by Django 5.0.1 on 2024-02-14 09:31

import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0006_locationreport'),
    ]

    operations = [
        migrations.CreateModel(
            name='MeetThePerson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=500, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('date', models.DateField(blank=True, null=True)),
                ('author', models.CharField(blank=True, max_length=200, null=True)),
                ('text', django_ckeditor_5.fields.CKEditor5Field(verbose_name='Text')),
            ],
        ),
    ]
